-- DB 초기화
DROP TABLE YOMUL_MEMBERS CASCADE CONSTRAINTS;
DROP TABLE YOMUL_FAVORITE_LISTS CASCADE CONSTRAINTS;
DROP TABLE YOMUL_TRADE_HISTORY CASCADE CONSTRAINTS;
DROP TABLE YOMUL_CHATS CASCADE CONSTRAINTS;
DROP TABLE YOMUL_PRODUCTS CASCADE CONSTRAINTS;
DROP TABLE YOMUL_TOWN_ARTICLES CASCADE CONSTRAINTS;
DROP TABLE YOMUL_NEAR_ARTICLES CASCADE CONSTRAINTS;
DROP TABLE YOMUL_VENDORS CASCADE CONSTRAINTS;
DROP TABLE YOMUL_VENDOR_NEWS CASCADE CONSTRAINTS;
DROP TABLE YOMUL_VENDOR_CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE YOMUL_VENDOR_REVIEWS CASCADE CONSTRAINTS;
DROP TABLE YOMUL_NOTICES CASCADE CONSTRAINTS;
DROP TABLE YOMUL_FAQ_CATEGORIES CASCADE CONSTRAINTS;
DROP TABLE YOMUL_FAQ_ARTICLES CASCADE CONSTRAINTS;
DROP TABLE YOMUL_QNA_CATEGORIES CASCADE CONSTRAINTS;
DROP TABLE YOMUL_QNA_ARTICLES CASCADE CONSTRAINTS;
DROP TABLE YOMUL_FILES CASCADE CONSTRAINTS;
DROP TABLE YOMUL_COMMENTS CASCADE CONSTRAINTS;
DROP SEQUENCE YOMUL_FILE_FILENO_SEQ;
DROP SEQUENCE YOMUL_NEAR_NO_SEQ;

-- 제약 조건 명명 규칙
-- 제약조건 축약어_자기테이블_상대테이블[_속성명]

-- 테이블 생성
-- 회원
CREATE TABLE YOMUL_MEMBERS(
  EMAIL VARCHAR2(100), -- 이메일
  PW VARCHAR2(50) CONSTRAINT NN_Y_M_PW NOT NULL, -- 비밀번호
  NICKNAME VARCHAR2(50) CONSTRAINT NN_Y_M_NICKNAME NOT NULL CONSTRAINT U_Y_M_NICKNAME UNIQUE, -- 별명
  HASHSALT VARCHAR2(100) CONSTRAINT NN_Y_M_HASHSALT NOT NULL, -- 해쉬 솔트
  PHONE VARCHAR2(30), -- 전화번호
  GENDER VARCHAR2(5), -- 성별
  INTRO VARCHAR2(500), -- 자기소개
  KAKAO_TOKEN VARCHAR2(100) UNIQUE, -- 카카오 로그인 토큰
  AUTHORITY VARCHAR2(10) DEFAULT 'USER' CONSTRAINT NN_Y_M_AUTHORUTY NOT NULL,
  MDATE DATE DEFAULT SYSDATE CONSTRAINT NN_Y_M_MDATE NOT NULL,
  CONSTRAINT PK_Y_M_EMAIL PRIMARY KEY(EMAIL)
);

-- 찜 목록
CREATE TABLE YOMUL_FAVORITE_LISTS(
  
);

-- 물건 정보
-- 물건 번호, 등록 유저 , 물건 글 제목, 물건 글 내용, 가격, 물건 판매 상태
CREATE TABLE YOMUL_PRODUCTS(
    NO VARCHAR2(10), -- 물건 번호
    SELLER VARCHAR2(100) CONSTRAINT NN_Y_P_SELLER NOT NULL, -- 등록자
    TITLE VARCHAR2(100) CONSTRAINT NN_Y_P_TITLE NOT NULL, -- 글 제목
    CONTENT VARCHAR2(500) CONSTRAINT NN_Y_P_CONTENT NOT NULL, -- 글 내용
    PRICE NUMBER(20) CONSTRAINT NN_Y_P_PRICE NOT NULL, -- 가격
    STATE VARCHAR2(20) CONSTRAINT NN_Y_P_STATE NOT NULL, -- 물건 상태
    CONSTRAINT PK_Y_P_NO PRIMARY KEY(NO),
    CONSTRAINT FK_Y_P_M_SELLER FOREIGN KEY (SELLER) REFERENCES YOMUL_MEMBERS(EMAIL)
);

-- 물건 거래 내역
-- 거래번호, 물건 번호, 판매자, 구매자, 거래 일시,
CREATE TABLE YOMUL_TRADE_HISTORY(
  NO VARCHAR2(10), -- 거래 번호
  PRODUCT_NO VARCHAR2(10)  CONSTRAINT NN_Y_T_H_NO NOT NULL, -- 물건 번호
  SELLER VARCHAR2(100)  CONSTRAINT NN_Y_TH_SELLER NOT NULL, -- 판매자
  BUYER VARCHAR2(100) CONSTRAINT NN_Y_TH_BUYER NOT NULL,  -- 구매자
  TRADE_DATE DATE CONSTRAINT NN_Y_TH_TDATE NOT NULL, -- 거래일시
  CONSTRAINT PK_Y_TH_NO PRIMARY KEY(NO),
  CONSTRAINT FK_Y_TH_PRODUCTS FOREIGN KEY(PRODUCT_NO) REFERENCES YOMUL_PRODUCTS(NO) ON DELETE CASCADE,
  CONSTRAINT FK_Y_TH_M_SELLER FOREIGN KEY(SELLER) REFERENCES YOMUL_MEMBERS(EMAIL) ON DELETE CASCADE,
  CONSTRAINT FK_Y_TH_M_BUYER FOREIGN KEY(BUYER) REFERENCES YOMUL_MEMBERS(EMAIL) ON DELETE CASCADE
);

-- 채팅
-- 번호(pk)not null, 수신자not null, 발신자not null, 내용not null, (사진?), 시간
CREATE TABLE YOMUL_CHATS(
    NO VARCHAR2(10), -- 채팅 번호 
    CHAT_FROM VARCHAR2(100) CONSTRAINT NN_Y_C_CHAT_FROM NOT NULL, -- 채팅 송신자
    CHAT_TO VARCHAR2(100) CONSTRAINT NN_Y_C_CHAT_TO NOT NULL, -- 채팅 수신자
    CONTENT VARCHAR2(500) CONSTRAINT NN_Y_C_CONTENT NOT NULL, -- 채팅 내용
    CDATE DATE DEFAULT SYSDATE CONSTRAINT NN_Y_C_CDATE NOT NULL, -- 채팅 일시
    CONSTRAINT PK_Y_CH_NO PRIMARY KEY(NO) ,
    CONSTRAINT FK_Y_CH_M_CHAT_FROM FOREIGN KEY (CHAT_FROM) REFERENCES YOMUL_MEMBERS(EMAIL),
    CONSTRAINT FK_Y_CH_M_CHAT_TO FOREIGN KEY (CHAT_TO) REFERENCES YOMUL_MEMBERS(EMAIL)
);

-- 동네생활 게시글
CREATE TABLE YOMUL_TOWN_ARTICLES(
  
);

-- 내 근처 게시글
CREATE TABLE YOMUL_NEAR_ARTICLES(
  NO VARCHAR2(10), --상품 게시글 번호
  EMAIL VARCHAR2(100) CONSTRAINT NN_Y_NA_EMAIL NOT NULL, -- 작성자
  TITLE VARCHAR2(50) CONSTRAINT NN_Y_NA_TITLE NOT NULL, -- 상품 제목
  CATEGORY VARCHAR2(20) CONSTRAINT NN_Y_NA_CATEGORY NOT NULL, -- 카테고리
  PRICE NUMBER(30), --가격(선택)
  HP VARCHAR2(50), --핸드폰 번호(선택)
  CONTENT VARCHAR2(1000) CONSTRAINT NN_Y_NA_CONTENT NOT NULL, --본문 내용
  NDATE DATE DEFAULT SYSDATE CONSTRAINT NN_Y_NA_NDATE NOT NULL, --작성 일자
  CHATCHECK NUMBER(1) DEFAULT 0 CONSTRAINT NN_Y_NA_CHATCHECK NOT NULL,    -- 채팅 금지 여부 DEFAULT 0 
  CONSTRAINT PK_Y_NA_NO PRIMARY KEY(NO),
  CONSTRAINT FK_Y_NA_EMAIL FOREIGN KEY (EMAIL) REFERENCES YOMUL_MEMBERS(EMAIL)
);

-- 업체 정보
CREATE TABLE YOMUL_VENDORS(
  
);

-- 업체 소식
CREATE TABLE YOMUL_VENDOR_NEWS(
  
);

-- 업체 단골
CREATE TABLE YOMUL_VENDOR_CUSTOMERS(
  
);

-- 업체 후기
CREATE TABLE YOMUL_VENDOR_REVIEWS(
  
);

-- 공지사항
CREATE TABLE YOMUL_NOTICES(
    NO VARCHAR2(10), -- 글 번호
    EMAIL VARCHAR2(100) CONSTRAINT NN_Y_N_EMAIL NOT NULL, -- 작성자
    TITLE VARCHAR2(100) CONSTRAINT NN_Y_N_TITLE NOT NULL, -- 제목
    CONTENT VARCHAR2(400) CONSTRAINT NN_Y_N_CONTENT NOT NULL, -- 내용
    NDATE DATE DEFAULT SYSDATE CONSTRAINT NN_Y_N_NDATE NOT NULL, -- 작성일자
    CONSTRAINT PK_Y_N_NO PRIMARY KEY(NO),
    CONSTRAINT FK_Y_N_MEMBERS FOREIGN KEY (EMAIL) REFERENCES YOMUL_MEMBERS(EMAIL)
);

-- FAQ 카테고리
CREATE TABLE YOMUL_FAQ_CATEGORIES(
    NO NUMBER(4), -- 카테고리 코드
    CONTENT VARCHAR2(100) CONSTRAINT NN_Y_FC_CONTENT NOT NULL, -- 카테고리 내용
    CONSTRAINT PK_Y_FC_NO PRIMARY KEY (NO)
);

-- FAQ 게시글
CREATE TABLE YOMUL_FAQ_ARTICLES(
    NO VARCHAR2(10), -- 글 번호
    CATEGORY NUMBER(4) CONSTRAINT NN_Y_FA_CATEGORY NOT NULL, -- 카테고리
    TITLE VARCHAR2(100) CONSTRAINT NN_Y_FA_TITLE NOT NULL, -- 제목
    CONTENT VARCHAR2(400) CONSTRAINT NN_Y_FAQ_ARTICLES_CONTENT NOT NULL, -- 내용
    CONSTRAINT PK_Y_FA_NO PRIMARY KEY (NO),
    CONSTRAINT FK_Y_FA_FAQ_CATEGORIES FOREIGN KEY (CATEGORY) REFERENCES YOMUL_FAQ_CATEGORIES(NO)
);

-- QNA 카테고리
CREATE TABLE YOMUL_QNA_CATEGORIES(
    NO NUMBER(4), -- 코드
    CONTENT VARCHAR2(100) CONSTRAINT NN_Y_Q_CATEGORIES NOT NULL, -- 카테고리 내용
    CONSTRAINT PK_Y_QC_NO PRIMARY KEY (NO)
);

-- QNA 게시글
CREATE TABLE YOMUL_QNA_ARTICLES(
    NO VARCHAR2(10), -- 글 번호
    WRITER VARCHAR2(100) CONSTRAINT NN_Y_QA_WRITER NOT NULL, -- 작성자 이메일
    WDATE DATE DEFAULT SYSDATE CONSTRAINT NN_Y_QA_WDATE NOT NULL, -- 작성 일자
    CATEGORY NUMBER(4) CONSTRAINT NN_Y_QA_CATEGORY NOT NULL, -- 작성 글 카테고리
    TITLE VARCHAR2(100) CONSTRAINT NN_Y_QA_TITLE NOT NULL, -- 제목
    CONTENT VARCHAR2(400) CONSTRAINT NN_Y_QA_CONTENT NOT NULL, -- 내용
    RDATE DATE, -- 답변 날짜
    RWRITER VARCHAR2(100), -- 답변 작성자 이메일
    REPLY VARCHAR2(400), -- 답변 작성 내용
    CONSTRAINT PK_Y_QA_NO PRIMARY KEY (NO),
    CONSTRAINT FK_Y_QA_M_WRITER FOREIGN KEY (WRITER) REFERENCES YOMUL_MEMBERS(EMAIL),
    CONSTRAINT FK_Y_QA_M_RWRITER FOREIGN KEY (RWRITER) REFERENCES YOMUL_MEMBERS(EMAIL),
    CONSTRAINT FK_Y_QA_QC_CATEGORY FOREIGN KEY (CATEGORY) REFERENCES YOMUL_QNA_CATEGORIES(NO)
);

-- 업로드 된 파일 테이블. 실제로 저장된 파일 명은 ('게시글 번호'_'파일 번호'_'파일 명') 식으로 저장 ex(n001_1_example_jpg)
--글 번호(예=p-001, n-005, t-007)not null, 파일번호(pk)not null, n파일
CREATE TABLE YOMUL_FILES(
    ARTICLE_NO VARCHAR2(10) CONSTRAINT NN_Y_F_ARTICLE_NO NOT NULL, -- 작성된 게시글 번호
    NO NUMBER(10), -- 파일 번호
    FILENAME VARCHAR2(100) CONSTRAINT NN_Y_F_FILENAME NOT NULL, -- 파일 명
    CONSTRAINT PK_Y_F_NO PRIMARY KEY (NO)
    
);

-- 댓글
CREATE TABLE YOMUL_COMMENTS(
  NO NUMBER(10), -- 댓글 번호 
  ARTICLE_NO VARCHAR2(10) CONSTRAINT NN_Y_CO_ARTICLE_NO NOT NULL, -- 댓글 달리는 게시판명
  EMAIL VARCHAR2(100) CONSTRAINT NN_Y_CO_EMAIL NOT NULL, -- 작성자 이메일
  CONTENT VARCHAR2(1000) CONSTRAINT NN_Y_CO_CONTENT NOT NULL, -- 작성 내용
  WDATE DATE DEFAULT SYSDATE CONSTRAINT NN_Y_CO_WDATE NOT NULL, -- 작성일자
  CONSTRAINT PK_Y_CO_NO PRIMARY KEY (NO),
  CONSTRAINT FK_Y_CO_M_EMAIL FOREIGN KEY(EMAIL) REFERENCES YOMUL_MEMBERS(EMAIL)
);

-- 회원 번호 시퀀스 생성
CREATE SEQUENCE YOMUL_FILE_NO_SEQ
START WITH 1 -- 1부터 시작
INCREMENT BY 1 -- 1씩 증가
CACHE 2; -- 메모리에 미리 올려 놓을 인덱스 개수. 비정상 종료되면 LAST_NUMBER가 2씩 증가

-- 내 근처 게시글 시퀀스 생성
CREATE SEQUENCE YOMUL_NEAR_NO_SEQ
START WITH 1 -- 1부터 시작
INCREMENT BY 1 -- 1씩 증가
CACHE 2;



-- FAQ 카테고리 데이터 생성
INSERT INTO YOMUL_FAQ_CATEGORIES(NO, CONTENT) VALUES(1, '운영정책');
INSERT INTO YOMUL_FAQ_CATEGORIES(NO, CONTENT) VALUES(2, '계정/인증');
INSERT INTO YOMUL_FAQ_CATEGORIES(NO, CONTENT) VALUES(3, '구매/판매');
INSERT INTO YOMUL_FAQ_CATEGORIES(NO, CONTENT) VALUES(4, '거래 품목');
INSERT INTO YOMUL_FAQ_CATEGORIES(NO, CONTENT) VALUES(5, '거래 매너');
INSERT INTO YOMUL_FAQ_CATEGORIES(NO, CONTENT) VALUES(6, '이벤트/초대');
INSERT INTO YOMUL_FAQ_CATEGORIES(NO, CONTENT) VALUES(7, '이용 제재');
INSERT INTO YOMUL_FAQ_CATEGORIES(NO, CONTENT) VALUES(8, '기타');
INSERT INTO YOMUL_FAQ_CATEGORIES(NO, CONTENT) VALUES(9, '비즈프로필');
INSERT INTO YOMUL_FAQ_CATEGORIES(NO, CONTENT) VALUES(10, '동네생활');
INSERT INTO YOMUL_FAQ_CATEGORIES(NO, CONTENT) VALUES(11, '지역 광고');
INSERT INTO YOMUL_FAQ_CATEGORIES(NO, CONTENT) VALUES(12, '채팅');

-- QNA 카테고리 데이터 생성
INSERT INTO YOMUL_QNA_CATEGORIES(NO, CONTENT) VALUES(1, '거래 환불/분쟁 및 사기 신고');
INSERT INTO YOMUL_QNA_CATEGORIES(NO, CONTENT) VALUES(2, '계정 문의');
INSERT INTO YOMUL_QNA_CATEGORIES(NO, CONTENT) VALUES(3, '판매 금지/거래 품목 문의');
INSERT INTO YOMUL_QNA_CATEGORIES(NO, CONTENT) VALUES(4, '매너평가, 매너온도, 거래후기 관련 문의');
INSERT INTO YOMUL_QNA_CATEGORIES(NO, CONTENT) VALUES(5, '게시글 노출, 미노출 문의');
INSERT INTO YOMUL_QNA_CATEGORIES(NO, CONTENT) VALUES(6, '채팅, 알림 문의');
INSERT INTO YOMUL_QNA_CATEGORIES(NO, CONTENT) VALUES(7, '앱 사용/거래 방법 문의');
INSERT INTO YOMUL_QNA_CATEGORIES(NO, CONTENT) VALUES(8, '동네 생활(커뮤니티) 문의');
INSERT INTO YOMUL_QNA_CATEGORIES(NO, CONTENT) VALUES(9, '지역 광고 문의');
INSERT INTO YOMUL_QNA_CATEGORIES(NO, CONTENT) VALUES(10, '비즈프로필(등록, 이용) 문의');
INSERT INTO YOMUL_QNA_CATEGORIES(NO, CONTENT) VALUES(11, '검색 문의');
INSERT INTO YOMUL_QNA_CATEGORIES(NO, CONTENT) VALUES(12, '기타 문의');
INSERT INTO YOMUL_QNA_CATEGORIES(NO, CONTENT) VALUES(13, '오류 제보');
INSERT INTO YOMUL_QNA_CATEGORIES(NO, CONTENT) VALUES(14, '개선/제안');